### ISSUE TITLE
Aspirational use case: [C]Worthy mCDR OAE Atlas dataset

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/VirtualiZarr#132]
The reason I made this package is to handle one particularly challenging use case - the [[C]Worthy](https://www.cworthy.org/) mCDR Atlas - which I still haven't done. Once it's done I plan to write a blog post talking about it, and maybe add it as a usage example to this repository.

This dataset has some characteristics that make it really challenging to kerchunk/virtualize[^1]:
- It's ~50TB compressed on-disk,
- It has ~500,000 netCDF files(!), each with about 40 variables,
- The largest variables are 3-dimensional, and require concatenation along an additional 3 dimensions, so the resulting variables are 6-dimensional,
- It has time encoding on some coordinates.

This dataset is therefore comparable to some of the largest datasets already available in Zarr (at least in terms of the number of chunks and variables, if not on-disk size), and is very similar to the pathological case described in #104 

> 24MB per array means that even a really big store with 100 variables, each with a million chunks, still only takes up 2.4GB in memory - i.e. your xarray "virtual" dataset would be ~2.4GB to represent the entire store.

**If we can virtualize this we should be able to virtualize most things** 💪

---

To get this done requires many features to be implemented:
- [x] Everything in the MVP of this package (https://github.com/zarr-developers/VirtualiZarr/issues/2),
- [ ] Good performance https://github.com/zarr-developers/VirtualiZarr/issues/104, including:
  - [ ] During reference generation (so might need https://github.com/zarr-developers/VirtualiZarr/pull/87)
  - [ ] For the in-memory representation (https://github.com/zarr-developers/VirtualiZarr/issues/33)
  - [ ] Writing out to kerchunk parquet format (https://github.com/zarr-developers/VirtualiZarr/pull/110)
- [ ] Effective parallelization of byte range generation across the many files (https://github.com/zarr-developers/VirtualiZarr/issues/95), possibly using https://github.com/zarr-developers/VirtualiZarr/issues/123,
- [ ] Handling of variables with time encoding (https://github.com/zarr-developers/VirtualiZarr/issues/117)
- [ ] "Inlining" of some variables for performance when reading (else all the 3 concatenation coordinates will have chunks of length 1) (#73)
- [ ] Optionally using `combine_by_coords` to handle the 3-dimensional concatenation, which would require #18,
- [ ] A way to get the references files onto S3, either via #46 or generating on HPC, changing the paths to the corresponding S3 URLs using #130, and moving the altered reference files to the cloud manually.

Additionally once zarr-python actually understands some kind of chunk manifest, I want to also go back and create an actual zarr store for this dataset. That will additionally require:
- [ ] The zarr-python storage transformer + chunk manifest stuff to actually be implemented,
- [ ] Ideally not having to re-do the reference generation, instead using https://github.com/zarr-developers/VirtualiZarr/pull/119 before calling `.virtualize.to_zarr()`,
- [ ] The ability to write out selected variables as normal compressed zarr arrays on-disk (https://github.com/zarr-developers/VirtualiZarr/issues/62#issuecomment-2089141712).

[^1]: In fact pretty much the only ways in which this dataset could be worse is if it had differences in encoding between netCDF files, variable-length chunks, or netCDF groups, but thankfully it has none of those 😅
