### ISSUE TITLE
Initial release checklist

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/VirtualiZarr#2]
What's here so far is a work-in-progress. I will consider this issue closed once the example in the Readme runs successfully.

For this we need:

- [x] Definition of a `ChunkManifest`
- [x] Definition of a `ManifestArray`
- [x] Concatenation of `ManifestArrays` through merging their manifests
- [x] Creation of `ManifestArrays` from kerchunk reference dicts
- [x] `ds_from_kerchunk_reference_dict` function
- [x] `open_dataset_via_kerchunk` function to read byte ranges and translate them to `ManifestArray` objects
- [x] Correct handling of concatenation in xarray (#34)
- [x] Option to avoid creating pesky indexes (see #14)
- [x] Xarray accessor to reconstruct kerchunk reference dicts from merged manifests (https://github.com/TomNicholas/VirtualiZarr/pull/28)
- [x] Serialize the dicts to disk as json

This list would get us the ability to do this:

```python
from virtualizarr import open_dataset_via_kerchunk

datasets = [open_dataset_via_kerchunk(filepath, no_indexes=True) for filepath in files]

combined = xr.combine_nested(datasets)

combined.virtualize.to_kerchunk(format='json')

# now can read using kerchunk mapper like normal
```

For the initial version we do _not_ need:
- [ ] Xarray backend entrypoint plugin (this is just syntactic sugar) (#35)
- [ ] Automatic inferring of concatenation order (see #18)
- [x] Writing out to parquet (https://github.com/TomNicholas/VirtualiZarr/issues/72)
- [x] Automatic detection of different file formats (see #10)
- [ ] Anything that requires zarr development, e.g. v3 support, variable-length chunking, concatenation of different codecs

Without this latter list we notably can't do `combine_by_coords` and we can't do `open_dataset(filepath, engine='virtualizarr')`.

**Comment by TomNicholas** [comment]
(I just updated this to be much clearer about what the "MVP" involves)

**Comment by TomNicholas** [comment]
I'm ready to release this, but @MSanKeys963 says we can move this repo into the [`zarr-developers`](https://github.com/zarr-developers) github org, and it would be great to do that move first 🙏

**Comment by jbusecke** [comment]
Adding a +1 here to move and release. I am working with @sashakames to prototype virtualizarr usage [within ESGF](https://github.com/jbusecke/esgf-virtual-zarr-data-access) and It would be great if we could pin versions.

**Comment by TomNicholas** [comment]
It's been moved!

**Comment by TomNicholas** [comment]
Now we've released v1.0 on PyPI and conda-forge with all the above initial features. The later features are all tracked by various issues.
